version : "3.8"

services :
  data-streamlit :
    build : 
      context : ./app/data-streamlit
    volumes : 
      - ./data:/app/streamlit
    tty : true #To allow access to the service with Terminal 
    ports : 
      #HTTP 
      - target : 8501
      - published : 8501
      - protocole : tcp 
      
